name: CD maasglobal-schema-generator-ajv

on:
  push:
    branches:
      - main
    paths:
      - 'maasglobal-schema-generator-ajv/package.json'
      - '.github/workflows/cd-maasglobal-schema-generator-ajv.yml'

defaults:
  run:
    working-directory: maasglobal-schema-generator-ajv

env:
  NODE_AUTH_TOKEN: ${{ secrets.PUBLIC_NPM_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    name: publish
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org"
      - name: Install Dependencies
        run: |
          yarn
      - name: Deploy to Registry
        run: |
          yarn deploy-npm
